export const artifacts = [
  {
    name: "Comparison map",
    owner: "Product Marketing",
    action: "Re-score price/value",
    risk: "High",
    status: "Draft ready",
    detail: "Competitive positioning",
    proposed: "Refresh the competitor price/value row with the captured source and timestamp.",
  },
  {
    name: "Pricing battlecard",
    owner: "Product Marketing",
    action: "Draft response",
    risk: "Medium",
    status: "Draft ready",
    detail: "Sales objection handling",
    proposed: "Add an evidence-cited response for the competitor's new price point; do not invent a discount.",
  },
  {
    name: "Deal desk guidance",
    owner: "RevOps",
    action: "Review discount guardrail",
    risk: "High",
    status: "Draft ready",
    detail: "Commercial operations",
    proposed: "Review whether the current discount guardrail still protects the intended price/value position.",
  },
  {
    name: "Executive weekly brief",
    owner: "Product Marketing",
    action: "Add market signal",
    risk: "Low",
    status: "Draft ready",
    detail: "Market narrative",
    proposed: "Include the observed competitor price change with source, timestamp, and confidence.",
  },
];

export const demoEvidence = {
  source_id: "competitor/pricing",
  source_name: "Competitor pricing snapshot",
  before: "Competitor Pro starts at $49 per seat per month.",
  after: "Competitor Pro starts at $59 per seat per month.",
  evidence_hash: "3b2df1ed8f635d1cc7ab425f675df0baa9bac941aaeddbfbca81ecada501d957",
  confidence: 0.99,
  snapshot_label: "Synthetic competitor fixture · competitor/pricing",
  snapshot_hash: "108725c5f3faf839e5df6e74e3fdec606e62520c337ce858ffed5ae0f7a6e767",
  source_url: "https://raw.githubusercontent.com/mikeyerke/driftline/main/fixtures/competitor-pricing-after.txt",
  data_mode: "synthetic_demo",
};
